name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Docker hub login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Build the Docker image
      run: docker build -t leehuor/nextjs:latest . --file Dockerfile

    - name: Push Image
      run: docker push leehuor/nextjs:latest
    - name: Remove container
      run: docker run --restart=always --name nextjs -p 3001:3001 nextj:latest
